### ISSUE TITLE
Installation instructions outdated and missing dependencies in the PyPI package

### ISSUE THREAD

**Issue by dmalzl** [menchelab/CartoGRAPHs#4]
I tried installing cartoGRAPHs using the outlined instructions in the README.md and after some trial and error which was mainly due to me wanting to use conda environments instead of python venvs I also succeeded. However, since there is a PyPI version of cartoGRAPHs I don't see the benefit of creating a venv and installing requirements first as pip should take care of this anyway. In my opinion the usage of any venv should be a choice of the user. Furthermore, creating a conda environment and installing just using pip worked fine until importing the module where `pymysql` and `shapely` were missing and had to be manually installed.

**Comment by chris-huetter** [comment]
Package issues should be resolved with version 2.0.0
